<template>
  <div>
    <div>
      <a :href="`https://wa.me/${user.whatsapp}?text=${encodeURI(setTemplate(user))}`" target="_blank">redirect to whatsapp {{ user.whatsapp }}</a>
    </div>
    <div><textarea name="" id="" cols="135" rows="10" :value="setTemplate(user)" disabled></textarea></div>
    <div v-if="user" :id="`template-${user.email}`" style="display: none">
      {{ setTemplate(user) }}
    </div>
  </div>
</template>

<script>
export default {
  props: {
    user: {
      type: Object,
      default: {
        name: "Udin",
        email: "Udin Penyok@mail",
        whatsapp: "628293948324",
        price: "Rp53.000",
        reminderDate: "17 Agustus 2021",
        expiredDate: "24 Agustus 2021"
      }
    },
  },
  methods: {
    setTemplate(user) {
      return `Halo kak *${user.name}*,\n`
            + `Masa berlangganan Netflix Paket Premium Group kamu telah memasuki satu bulan, dan akan berakhir pada *${user.expiredDate}*.\n`
            + "Untuk berlangganan satu bulan ke depan, segera lakukan pembayaran ke rekening berikut.\n\n"
            + "----------------------------------------------------\n"
            + "*MANDIRI*\n"
            + "No. Rekening: *1150007389705*\n"
            + "Atas nama: *PT. Trivamas Tekno Solusindo*\n\n"
            + "*JENIUS*.\n"
            + "No. Rekening: *90390072028*\n"
            + "Atas nama: *AADILAH AZIZ*\n\n"
            + "*GOPAY / OVO / DANA / LINKAJA*.\n"
            + "No. Handphone: *085774642738*\n"
            + "Atas nama: *SEAKUN ID* / *EKA PUSNA*\n\n"
            + "----------------------------------------------------\n"
            + "Nominal Pembayaran\n"
            + `*${user.price}*\n`
            + "----------------------------------------------------\n\n"
            + "Setelah melakukan pembayaran, konfirmasi dengan cara :\n"
            + "1. Kirim bukti transfer ke nomor Whatsapp operasional kami di 082124852227 (klik https://bit.ly/2SbJYrx)\n"
            + "2. Isi format konfirmasi berikut untuk memudahkan kami melakukan pengecekan :\n"
            + "- Bank tujuan: *Mandiri/Gopay/OVO/LinkAja/DANA/Jenius*\n"
            + "- Nama rekening pengirim: *Budi* (contoh)\n\n"
            + `Akun dan Profile Netflix akan dinonaktifkan jika tidak melakukan pembayaran setelah *${user.expiredDate}*. Terimakasih 🙏🏻\n\n`
            + "_Note. Reminder generated by system, jika kaka sudah merasa membayar, reminder bisa diabaikan saja_"
    }
  }
}
</script>

<style lang="scss" scoped>

</style>